Code/Posts/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Business;
using Model;

namespace Posts.Controllers
{
    public class CommentsController : Controller
    {
        private CommentsBLL _comment = new CommentsBLL();

        /// <summary>
        /// GET method to validate Comments by Post
        /// </summary>
        /// <param name="idPost"> int value Post Id</param>
        /// <returns>Redirect to Comment Index to display all comments</returns>
        public ActionResult Index(int? idPost)
        {
            if (idPost == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var comments = _comment.GetCommentsByPost((int)idPost);
            ViewBag.idPost = idPost;
            return View(comments.ToList());
        }

        /// <summary>
        /// POST method to create a new comment
        /// </summary>
        /// <param name="comment"> comment object with comment1 data and fkpost</param>
        /// <returns>Redirect to comment index</returns>
        [HttpPost]
        public ActionResult Create([Bind(Include = "Comment1,FkPost")] Comment comment)
        {
            if(!string.IsNullOrEmpty(comment.Comment1))
                _comment.CreateComment(comment.Comment1, comment.FkPost);
            
            return RedirectToAction("index", new { idPost = comment.FkPost });
        }
        
    }
}

Code/Posts/Views/Comments/Index.cshtml
@model IEnumerable<Model.Comment>

@{
    ViewBag.Title = "Index";
}

<h2>Comments </h2>
<div class="row">
    @using (Html.BeginForm("Create", "Comments", FormMethod.Post, new { style = "width: 100%" }))
    {
        <input type="hidden" name="FkPost" value="@ViewBag.idPost">
        <div class="form-group" style="width: 100%">
            <div class="col-md-12">
                <label for="Comment1">Comment</label>
                <textarea class="form-control rounded-0" id="Comment1" rows="10" name="Comment1"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12" style="margin-top: 10px">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Back to Post", "Details", "Posts", new { id = @ViewBag.idPost }, new { @class = "btn btn-primary" })
            </div>
        </div>
    }
</div>

        
        <div class="card" style="margin-top: 10%">
            <ul class="list-group list-group-flush">
                @foreach (var item in Model)
                {
                    <li class="list-group-item">
                        <h6 class="card-subtitle mb-2 text-muted">@item.CreationDate</h6>
                        @item.Comment1
                    </li>
                }
            </ul>
        </div>