Code/Posts/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Linq;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Business;
using Model;

namespace Posts.Controllers
{
    public class UsersController : Controller
    {
        private UsersBLL _user = new UsersBLL();

        /// <summary>
        /// POST method to validate the username and password and store identity data
        /// </summary>
        /// <param name="UserName"> string value userName</param>
        /// <param name="Password"> String value no encrypted password</param>
        /// <returns>Redirect to home if is false or to post according the user rol</returns>
        [HttpPost]
        [Route("ValidateUser")]
        public ActionResult ValidateUser(string UserName, string Password)
        {
            try
            {
                if (string.IsNullOrEmpty(UserName) || string.IsNullOrEmpty(Password))
                {
                    return RedirectToAction("index", "home");
                }

                User ValidUser = _user.ValidateUser(UserName, Password);

                if (ValidUser != null)
                {
                    var identity = new ClaimsIdentity(new[] {
                            new Claim(ClaimTypes.PrimarySid, ValidUser.Id.ToString()),
                            new Claim(ClaimTypes.Name, ValidUser.Name),
                            new Claim(ClaimTypes.Role, ValidUser.FkRol.ToString()),
                        },
                        "ApplicationCookie");

                    var ctx = Request.GetOwinContext();
                    var authManager = ctx.Authentication;

                    authManager.SignIn(identity);
                    if(ValidUser.FkRol == 1)
                        return RedirectToAction("index", "posts");
                    else
                        return RedirectToAction("Approved", "posts");
                    
                }
                return RedirectToAction("index", "home");
            }
            catch (Exception exp)
            {
                return RedirectToAction("index", "home");
            }
        }

        /// <summary>
        /// GET method LogOut a user and remove identity
        /// </summary>
        /// <returns>Redirect to home</returns>
        [Route("LogOut")]
        public ActionResult LogOut()
        {
            try
            {
                var ctx = Request.GetOwinContext();
                var authManager = ctx.Authentication;

                authManager.SignOut("ApplicationCookie");
                return RedirectToAction("index", "home");
            }
            catch (Exception exp)
            {
                return RedirectToAction("index", "home");
            }
        }
    }
}

Code/Posts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Published Posts", "Index", "Home")</li>
                    @if (User.IsInRole("1"))
                    {
                        <li>@Html.ActionLink("My Posts", "index", "Posts")</li>
                    }
                    else if (User.IsInRole("2"))
                    {
                        <li>@Html.ActionLink("Posts Processed", "Approved", "Posts")</li>
                        <li>@Html.ActionLink("Pending Posts", "Pending", "Posts")</li>
                    }

                    @if (!Request.IsAuthenticated)
                    {
                        <li class="dropdown order-1" style="margin-top: 7px">
                            <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle" style="background-color: transparent; color: white;">Login <span class="caret"></span></button>
                            <ul class="dropdown-menu dropdown-menu-right mt-2" style="min-width: 250px; border-radius: 22px;">
                                <li class="px-3 py-2" style="margin: 10%;">
                                    @using (Html.BeginForm("ValidateUser", "Users", FormMethod.Post))
                                    {
                                        <div class="form-group">
                                            <input id="UserName" name="UserName" placeholder="UserName" class="form-control form-control-sm" type="text" required="">
                                        </div>
                                        <div class="form-group">
                                            <input id="Password" name="Password" placeholder="Password" class="form-control form-control-sm" type="password" required="">
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                                        </div>
                                    }
                                </li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("LogOut", "LogOut", "Users")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>